### ISSUE TITLE
Cat drawable todo list

### ISSUE THREAD

**Issue by snapcat** [snapcat/CatStax#5]
Tracks whether a cat has an associate drawable/image

- [ ] cat0    (size 2, little blue)
- [ ] cat1    (size 3, little pink)
- [ ] cat2    (2x2, size 4, dark blue, standing)
- [ ] cat3    (size 4, white, lying)
- [ ] cat4    (3x2, size 6, purple)
- [ ] cat5    (size 6, jade)
- [ ] cat6    (size 6, pink)
- [ ] cat7    (size 7, yellow)
- [ ] cat8    (size 7, long pink)
- [ ] cat9   (size 8, black)
- [ ] cat10  (size 9, blue)
- [ ] cat11  (size 10, green)
